services:
  postgres-airflow:
    image: postgres:15
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile_airflow
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    volumes:
      - ./Pipelines:/opt/airflow/Pipelines
      - ./Funcoes:/opt/airflow/Funcoes
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/Pipelines/dags"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow"
      AIRFLOW__WEBSERVER__SECRET_KEY: "admin123"
      PYTHONPATH: "/opt/airflow/Pipelines:/opt/airflow"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username airflow --password airflow --firstname admin --lastname user --role Admin --email admin@email.com &&
      airflow webserver
      "
    depends_on:
      - postgres-airflow

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile_airflow
    container_name: airflow-scheduler
    volumes:
      - ./Pipelines:/opt/airflow/Pipelines
      - ./Funcoes:/opt/airflow/Funcoes
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/Pipelines/dags"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow"
      AIRFLOW__WEBSERVER__SECRET_KEY: "admin123"
      PYTHONPATH: "/opt/airflow/Pipelines:/opt/airflow"
    command: >
      bash -c "
      sleep 10 &&      
      airflow scheduler
      "
    depends_on:
      - airflow-webserver

volumes:
  postgres_airflow_data: